//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CastIt.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CASTIT_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define IDD_CONFIG_DIALOG               130
#define IDD_ADDSERVER                   131
#define IDD_FTPINFO                     133
#define IDR_MENU1                       134
#define IDI_HELP                        146
#define IDI_EDIT                        167
#define IDI_SATALITE                    168
#define IDI_SCAST                       169
#define IDI_NETWORK                     170
#define IDI_ICECAST2                    171
#define IDI_MYSQL                       172
#define IDR_POPUP                       182
#define IDI_EXIT                        190
#define IDI_CONFIG                      191
#define IDI_SERVER                      192
#define IDI_UPDATE_CASTIT               194
#define IDI_SYS_TRAY                    195
#define IDI_ICECAST2_32X32              196
#define IDI_SCAST_32X32                 197
#define IDI_CASTIT                      198
#define IDI_HOME                        223
#define IDC_HAND                        225
#define IDI_ADD_SERVER1                 230
#define IDI_ADD_SERVER2                 231
#define IDI_SYS_TRAY2                   232
#define IDI_CLASS1                      233
#define IDI_MAINFRAME                   236
#define IDI_ADD_SERVER                  239
#define IDI_TIMER                       240
#define IDB_SKIN_MSN                    248
#define IDB_CHECKBOXES                  251
#define IDI_CLEAR_LOG                   252
#define IDI_STEAMCAST                   253
#define IDC_SERVER_LIST                 1000
#define IDC_MY_HOSTNAME                 1002
#define IDC_HIDEAPP                     1002
#define IDC_MYSQL_FLAG                  1003
#define IDC_MY_USERNAME                 1004
#define IDC_MY_PASSWORD                 1005
#define IDC_MY_DATABASE                 1006
#define IDC_MY_TABLEPREFIX              1007
#define IDC_AGGREGATE                   1008
#define IDC_DELETE_SONGHISTORY_INTERVAL 1009
#define IDC_VERIFY_CONNECTION           1010
#define IDC_CREATE_TABLES               1011
#define IDC_SERVERURL                   1012
#define IDC_CALLURL                     1012
#define IDC_SERVERPASSWORD              1013
#define IDC_GENERATETEMPLATE            1013
#define IDC_SERVERTYPE                  1014
#define IDC_SERVERTYPE2                 1015
#define IDC_GETSTATS                    1016
#define IDC_SERVERTYPE3                 1016
#define IDC_POLLINTERVAL                1017
#define IDC_CLEAR_LOG                   1017
#define IDC_UPDATENOW                   1018
#define IDC_URL                         1019
#define IDC_MOUNTPOINT                  1020
#define IDC_TEMPLATEIN                  1021
#define IDC_TEMPLATEOUT                 1022
#define IDC_BROWSE1                     1023
#define IDC_BROWSE2                     1024
#define IDC_VIEWCGI                     1025
#define IDC_FTPINFO                     1026
#define IDC_FTPUSER                     1027
#define IDC_VIEWHELP                    1027
#define IDC_VIEWHELP1                   1027
#define IDC_FTPPASSWORD                 1028
#define IDC_VIEWHELP2                   1028
#define IDC_FTPHOST                     1029
#define IDC_VIEWHELP3                   1029
#define IDC_FTPDESTINATION              1030
#define IDC_VIEWHELP4                   1030
#define IDC_FTPTEMPLATE                 1031
#define IDC_VIEWHELP5                   1031
#define IDC_ADDSERVER                   1032
#define IDC_VIEWHELP6                   1032
#define IDC_CC_CHECK                    1035
#define IDC_CC_COM                      1038
#define IDC_UPDATE_CC                   1039
#define IDC_VERSION                     1040
#define ID_STATIC                       1047
#define IDC_CCLUB                       1063
#define IDC_CCMEM                       1064
#define IDC_LINK                        1066
#define IDC_MENU1                       1068
#define ID_CASTITHOME                   1070
#define IDC_BUTTON1                     1072
#define IDC_LOG                         1073
#define IDC_HOMEPAGELINK                1075
#define IDC_TAB                         1076
#define IDC_BWIDTH                      1077
#define ID_FILE_CONFIGURATION           32771
#define ID_FILE_EXIT                    32772
#define ID__INSERTNEWSERVERENTRY        32773
#define ID_MINIMIZE                     32773
#define ID__DELETE                      32774
#define ID_HELP2                        32775
#define IDC_CCINI                       32776
#define ID_POPUP_RESTORE                32777
#define IDC_CCLOG                       32778
#define IDC_CCINIBACKUP                 32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID__ADMIN                       32785
#define ID_ADMINPAGE                    32786
#define ID_PLAYSTREAM                   32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
